### ISSUE TITLE
Arithmatic operation resulted in an overflow

### ISSUE THREAD

**Issue by zaimsyaddad99** [H4rk3nz0/Peeper#1]
when i ran Peeper.exe in myside, i got overflow exception like this.

`->Keeper Target PID Found: xxxxx
->Searching...

Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr..ctor(Int64 value)
   at Program.Main(String[] args) in c:\Users\user\Desktop\Peeper\Peeper\Program.cs:line 135`

meanwhile Program.cs line 135 like this
`
--SNIPPET--
IntPtr address = new IntPtr(0x10000000000);
--SNIPPET--
`

do you know how to resolve this?

**Comment by H4rk3nz0** [comment]
Hi, I am only able to recreate your issue when I compile the the executable as x86 instead of x64 in Visual Studio.
Can you confirm your release CPU is set correctly?

![image](https://github.com/H4rk3nz0/Peeper/assets/54619779/23d8c1de-36e3-4cbb-bf47-eac1cea7973f)

**Comment by zaimsyaddad99** [comment]
wow that's solving my error. Thanks!

`dotnet Peeper.sln -c Release -p Platform=x64`

**Comment by H4rk3nz0** [comment]
Glad to hear that worked!
